apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense-tracker
data:
  PORT: "5000"
  DB_HOST: postgres-svc
  DB_PORT: "5432"
  DB_NAME: expense_tracker
  DB_USER: postgres
  ML_SERVICE_URL: http://ml-svc:8000
  ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173,http://15.207.145.213:30000
  JWT_EXPIRATION_MS: "86400000"
  NODE_ENV: production