apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: ML_IMAGE_TAG   # replaced by Jenkins
        ports:
        - containerPort: 8000