apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: expense-tracker
type: Opaque
data:
  DB_USER: dXNlcg==        # base64 of "user"
  DB_PASSWORD: cGFzcw==    # base64 of "pass"