[jenkins]
jenkins-server ansible_host=3.7.82.89

[k8s_master]
k8s-master ansible_host=13.205.168.194

[k8s_workers]
k8s-worker-1 ansible_host=15.207.145.213
k8s-worker-2 ansible_host=65.1.233.22

[k8s_all:children]
k8s_master
k8s_workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3