[jenkins]
jenkins-server ansible_host=13.203.69.188

[k8s_master]
k8s-master ansible_host=65.2.116.254

[k8s_workers]
k8s-worker-1 ansible_host=65.1.185.220
k8s-worker-2 ansible_host=13.201.171.55

[k8s_all:children]
k8s_master
k8s_workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3